version: "2"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
  kafka:
    depends_on:
      - zookeeper
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - '9092:9092'
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  silverbroccoli:
    build:
      context: .
    environment:
      env.kafka.bootstrapservers: 'kafka:9092'
    depends_on:
      - kafka
