spring:
  kafka:
    properties:
      security.protocol: ${env.kafka.securityprotocol}
      sasl.mechanism: ${env.kafka.saslmechanism}
  cloud:
    stream:
      kafka:
        binder:
          configuration:
            security.protocol: ${env.kafka.securityprotocol}
            sasl.mechanism: ${env.kafka.saslmechanism}