spring:
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: numbers-raw
          producer:
            # Provision new topics with 3 partitions.
            partitionCount: 3
        transformer-in-0:
          destination: numbers-raw
        transformer-out-0:
          destination: numbers-structured
          producer:
            partitionCount: 3
        consumer-in-0:
          destination: numbers-structured
      kafka:
        bindings:
          producer-out-0:
            producer:
              topic.properties:
                # Retain only 10,000 bytes. The default is unlimited (-1).
                retention.bytes: 10000
                # Retain messages for 2 days. The default is 7. -1 is unlimited.
                retention.ms: 172800000
        binder:
          brokers: ${env.kafka.bootstrapservers}
    function:
      # Separate function names with a _semicolon_.
      definition: producer;transformer;consumer