spring:
  cloud:
    stream:
      bindings:
        errorProneSupplier-out-0:
          destination: error-prone-numbers
        # This consumer shuffles failed messages to a DLQ. We must give it an
        # explicit group name, since the name of the DLQ is derived from the
        # topic and consumer group. See the kafka.bindings section as well.
        errorProneConsumer-in-0:
          destination: error-prone-numbers
          group: group1
          consumer:
            maxAttempts: 3
        debugErrorProneConsumer-in-0:
          destination: error.error-prone-numbers.group1
      kafka:
        bindings:
          errorProneConsumer-in-0:
            consumer:
              enableDlq: true
              # This is the default binder name:
              # dqlName: error.error-prone-numbers.group1
    function:
      # Separate function names with a _semicolon_.
      definition: errorProneSupplier;errorProneConsumer;debugErrorProneConsumer