spring:
  cloud:
    stream:
      bindings:
        producer-out-0:
          destination: numbers
        consumer-in-0:
          destination: numbers
      kafka:
        binder:
          brokers: ${env.kafka.bootstrapservers}
    function:
      # Separate function names with a _semicolon_.
      definition: producer;consumer