spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sb
    username: admin
    password: password

logging:
  level:
    root: ERROR
    com.github.tomboyo.silverbroccoli: INFO

sb:
  loggers.dlt:
    topics: input-high.DLT, input-low.DLT, other.DLT
    # dlt: not configured
    workers: 1
    # poll.timeout.ms: 100
    # max.attempts: 3
    kafkaConsumer:
      auto.offset.reset: earliest
      enable.auto.commit: false
      group.id: DltLoggers
      partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      isolation.level: read_committed
    kafkaProducer:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: com.github.tomboyo.silverbroccoli.kafka.JacksonObjectSerializer
  loggers.leftright:
    topics: left, right
    workers: 1
    kafkaConsumer:
      auto.offset.reset: earliest
      enable.auto.commit: false
      group.id: LeftRightLoggers
      partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    kafkaProducer:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: com.github.tomboyo.silverbroccoli.kafka.JacksonObjectSerializer
  auditors.high.priority:
    topics: input-high
    dlt: input-high.DLT
    workers: 1
    # TODO: batch.size (alias of max.poll.records)
    # TODO: enforce enable.auto.commit
    kafkaConsumer:
      auto.offset.reset: earliest
      enable.auto.commit: false
      group.id: Auditors
      max.poll.records: 5
      partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    kafkaProducer:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: com.github.tomboyo.silverbroccoli.kafka.JacksonObjectSerializer
  auditors.low.priority:
    topics: input-low
    dlt: input-low.DLT
    workers: 1
    kafkaConsumer:
      auto.offset.reset: earliest
      enable.auto.commit: false
      group.id: Auditors
      max.poll.records: 5
      partition.assignment.strategy: org.apache.kafka.clients.consumer.RoundRobinAssignor
      key.deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value.deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
    kafkaProducer:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: com.github.tomboyo.silverbroccoli.kafka.JacksonObjectSerializer