spring:
  kafka:
    # These properties are environment-specific. Set them in application-$PROFILE.yaml
    # bootstrap-servers:
    # properties:
    #   sasl:
    #     mechanism:
    #     login.callback.handler.class:
    #     jaas.config:
    #   security.protocol:
    producer:
      # Enable kafka transactions application-wide.
      transaction-id-prefix: 'tx-'
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.IntegerDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: java.util,java.lang,com.github.tomboyo.silverbroccoli